### ISSUE TITLE
Unable to get diff version  on oxidized-web with apache proxy

### ISSUE THREAD

**Issue by andretlemos** [ytti/oxidized-web#197] opened 2019-07-29 13:00 UTC
Hi,

i'm trying to get diff version on git files between different versions, such as version 7 and version 2 and I'm get the error below: 

Puma caught this error: can't modify frozen String (RuntimeError)
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `gsub!'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `block in inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `each'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `each_with_object'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `block in inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `each'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `each_with_object'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `block in inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `each'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `each_with_object'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `block in inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `each'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `each_with_object'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `block in inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `each'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `each_with_object'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `h'
(erb):272:in `block in pretty'
(erb):269:in `each'
(erb):269:in `pretty'
/usr/local/rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/erb.rb:864:in `eval'
/usr/local/rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/erb.rb:864:in `result'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:97:in `pretty'
/usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:34:in `rescue in call'
/usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:24:in `call'
/usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
/usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
/usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
/usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
/usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/urlmap.rb:66:in `block in call'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/urlmap.rb:50:in `each'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/urlmap.rb:50:in `call'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/builder.rb:153:in `call'
/usr/local/rvm/gems/ruby-2.3.8/gems/puma-3.11.4/lib/puma/configuration.rb:225:in `call'
/usr/local/rvm/gems/ruby-2.3.8/gems/puma-3.11.4/lib/puma/server.rb:632:in `handle_request'
/usr/local/rvm/gems/ruby-2.3.8/gems/puma-3.11.4/lib/puma/server.rb:446:in `process_client'
/usr/local/rvm/gems/ruby-2.3.8/gems/puma-3.11.4/lib/puma/server.rb:306:in `block in run'
/usr/local/rvm/gems/ruby-2.3.8/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

####################

This not happened when I'm connect directly on Puma web site and I'm using apache proxy.
Also the error doesn't appear if I got the default diff, such as version 5 and 4, 4 and 3.

**Comment by jameskirsop** [comment] 2019-09-30 01:47
I'm also seeing this Puma dump when trying to access a new node's diff or latest version.

**Comment by LibertineC** [comment] 2020-04-02 02:53
> I'm also seeing this Puma dump when trying to access a new node's diff or latest version with an Apache proxy in front of Puma.
> 
> When I try and access it locally via curl I get:
> `ArgumentError: wrong number of arguments (given 0, expected 1+)`

I have the same problem
output:  git

Have you solved the problem?
`ArgumentError: wrong number of arguments (given 0, expected 1+)`

**Comment by ytti** [comment] 2020-04-02 05:57
This is duplicate of ytti/oxidized#2049

**Closed by ytti** 2020-04-02 05:57 UTC
