### ISSUE TITLE
no useable nodes

### ISSUE THREAD

**Issue by cchance27** [ytti/oxidized-web#39] opened 2015-12-01 16:40 UTC
I can't for the life of me figure this out i'm getting returned the correct info from librenms, but oxidized refused to start running it just says no usable nodes... please help

curl -H 'X-Auth-Token: xxxxxxxxxxxxxxxxxxxxxxxxxxc' http://127.0.0.1/api/v0/oxidized
Returns the following....

[
    {
        "hostname": "ofcswitch-1",
        "os": "xos"
    },
    {
        "hostname": "ofcswitch-1",
        "os": "xos"
    }
]

/root/.config/oxidized/config 
username: usernameexample
password: passwordexample
debug: true
rest: 127.0.0.1:8888
input:
  default: ssh
  debug: false
  ssh:
    secure: false
output:
  default: file
  file:
    directory: /root/.config/oxidized/configs
source:
  default: http
  debug: true
  http:
    url: http://127.0.0.1/api/v0/oxidized
    scheme: http
    debug: true
    delimiter: !ruby/regexp /:/
    map:
      name: hostname
      model: os
    headers:
      X-Auth-Token: xxxxxxxxxxxxxxxxxxxxxxxxxxc

i even tried adding model_map: xos:xos but didn't work either still getting same error every time i try to start it

[root@librenms oxidized]# oxidized
source returns no usable nodes
/usr/local/share/gems/gems/oxidized-0.9.0/lib/oxidized/core.rb:23:in `initialize': source returns no usable nodes (Oxidized::Core::NoNodesFound)
        from /usr/local/share/gems/gems/oxidized-0.9.0/lib/oxidized/core.rb:12:in `new'
        from /usr/local/share/gems/gems/oxidized-0.9.0/lib/oxidized/core.rb:12:in `new'
        from /usr/local/share/gems/gems/oxidized-0.9.0/lib/oxidized/cli.rb:9:in `run'
        from /usr/local/share/gems/gems/oxidized-0.9.0/bin/oxidized:9:in `<top (required)>'
        from /usr/local/bin/oxidized:23:in `load'
        from /usr/local/bin/oxidized:23:in `<main>'

**Comment by ytti** [comment] 2015-12-01 17:48
My first guess is that it can't resolve either of the names, and ends up with 0 nodes.

**Comment by cchance27** [comment] 2015-12-01 21:24
I have them hardcoded into /etc/hosts and librenms contacts the same
devices by the same names resolving so its not that

My first guess is that it can't resolve either of the names, and ends up
with 0 nodes.

—
Reply to this email directly or view it on GitHub
<https://github.com/ytti/oxidized-web/issues/39#issuecomment-161045595>.

**Comment by ytti** [comment] 2015-12-01 21:45
I wonder if we even use /etc/hosts, we probably don't. 

Can you try IP addresses only?

Do you have anything in syslogs? I think it might complain there.

**Comment by supertylerc** [comment] 2015-12-28 05:13
@cchance27, are you still having this problem?  If so, could you please paste your config with proper formatting?  YAML is extremely picky about formatting, and bad formatting might cause an issue.  Unfortunately, it's hard to tell from the output you've pasted.

Also, this bug should be filed against [ytti/oxidized](https://github.com/ytti/oxidized) since it actually doesn't have anything to do with oxidized-web.

Thanks!

**Comment by supertylerc** [comment] 2015-12-31 02:46
Bug confirmed.

**Comment by supertylerc** [comment] 2015-12-31 02:52
I'm moving this to ytti/oxidized where it belongs.

**Comment by supertylerc** [comment] 2015-12-31 03:06
Closing as a duplicate of ytti/oxidized#255.

**Closed** 2015-12-31 03:06 UTC
Labels: bug, duplicate

**Comment by supertylerc** [comment] 2015-12-31 03:52
@cchance27:

I initially thought I was able to reproduce this, but I was not.  A working configuration is referenced at the end of ytti/oxidized#255.

If you continue to have issues, please:

* Try the same devices using the CSV source
* Reopen this issue if the CSV source works but HTTP does not
* Paste your config in code tags here
* Turn on debug logs
* Paste the output of `gem list --local oxidized`
* Paste the output of `oxidized`
