### ISSUE TITLE
ArgumentError at /node/version wrong number of arguments (given 0, expected 1+)

### ISSUE THREAD

**Issue by tokarenkos** [ytti/oxidized-web#236] opened 2023-04-19 13:54 UTC
I have Ruby 3.0 and oxidized 0.29.0 oxidized-web 0.13.1 Installed on Ubuntu 22.04.2.
When I clicking to "version" I had error with this messages

ArgumentError at /node/version wrong number of arguments (given 0, expected 1+)
file: versions.haml location: count line: 24

**Comment by mortzu** [comment] 2023-04-22 16:20
duplicate of #235

**Closed by mortzu** 2023-04-22 16:20 UTC

**Comment by bacala** [comment] 2023-05-15 13:44
The same issue was opened at oxidized, and already closed with comment, that this is an 'oxidized-web' issue.
Here again my comment, which maybe will help to troubleshoot the bug. I have tried to find the problem quickly, but it needs a bit more time. Maybe I will find it later, till then just my assumptions.

I have noticed the same issue. If you try to call it in json format it returns "node not found" which is actually the reason why we get ArgumenError. It tries to call .count on string instead of array. I would say that nodes.version doesn't work but the nodes.show yes.
